### ISSUE TITLE
Where is the data from?

### ISSUE THREAD

**Issue by JoshData** [CivilServiceUSA/us-house#8]
Hi there. You have a lot of data here, but no citations to where the data is from. If you're using data from https://github.com/unitedstates/congress-legislators/, directly or indirectly from other sources, please refrain from doing so until you provide attribution. Thanks. Better though would be to work with folks who are already doing this work, rather than duplicating effort!

**Comment by manifestinteractive** [comment]
This data was collected by hand from the direct sources online ( bioguide, opensectrets, govtrack, etc, etc ).  We had to wait until early this morning to fetch bioguide IDs as they were not available for verification until this morning. 

We’ve been doing this data for a few years now, and happy you somehow stumbled onto it within hours of our public release. Same thing happened two years ago, if I recall. 

While I understand your concern about consolidating efforts, Civil Services has specific needs and data attributes your project ( and others ) simply don’t offer. 

Feel free to use any of our additional data in your project.  Should be pretty easy to match up since we got it from the same public, free sources.  No need to attribute Civil Services if you do.  Heck, several hours were spent creating customs images too for each rep.  Have at those if it helps your team. 

We should be helping each other, like you said.

Closing this out since it was not really an issue with anything broken on our project.

**Comment by JoshData** [comment]
There's data in here that can only be found in the congress-legislators repo, so, again, please credit your sources.

**Comment by manifestinteractive** [comment]
BTW, since it looks like you’re associated with GovTrack, let me know if you’d prefer I remove your ID from our service.  The idea was to provide our API users a unique ID to connect to great services without actually using their data in our API ( just provide a way to get to that data if they want ). 

As you can see on our website, we link people directly to the source websites that provide helpful info.

Though I don’t think we’re using GovTrack at all for anything, other than retuning the sites IDs for elected officials via our API.  We got those IDs, the same way we got all the others.  Hitting the website, doing a search, grabbing the ID from the URL after verifying the match. 

I assume you got the info the same way :)

But ya, happy to remove GovTrack IDs if they’re private info or something.  Would certainly be one less thing we have to verify the morning of new elected officials taking office ;)

Didn’t think we needed to attribute your ID since that’s all we really have. 

I guess let me know either way.

**Comment by manifestinteractive** [comment]
I had volunteers collecting data, the bios should be from our US governments BioGuide listings. 

If you can provide which data you know is only available in your project, I’ll hapily remove it.  Might just be that one of our volunteers grabbed it by mistake while waiting for the government descriptions to populate.

**Comment by JoshData** [comment]
I'm not asking you to remove anything, only to stop pretending that you're doing all of the work yourself!

You have GovTrack IDs for new House members in your dataset. That information can only be found in a staging branch in the congress-legislators repository --- it's not even on GovTrack yet. You're welcome to use it. Just acknowledge that you actually got it from there and didn't collect it in the manner you described above.

**Comment by manifestinteractive** [comment]
Well, likely this was a volunteer trying to make sure we could link people to your service.  In my opinion, they went above and beyond in tracking down this info to help our users find your service IDs for use on your site.  This repo is part of our bigger API data set, and the GovTrack IDs were provided for those wishing to get more data outside our service. 

In all honesty it will hurt our API users that might have used that ID to get to your service as that was the only way we could connect them to you. 

But you’ve made your opinion clear, and I wish to respect your concerns.  Your service IDs are not going to be distributed by our service.  I’ll deploy a release this evening that removes your IDs from our system.

While I have no issues attributing data we did not create, our service only links to other services.  We do not actually store or collect anything other than public data used to link to these great services via our API and Website.

Honestly, IMO, it does not make sense to attribute an ID that literally has the service name right next to it and can only be used by visiting that site.  Like, what else are people going to do with that info, other than use it to visit the site.

¯\_(ツ)_/¯
